### ISSUE TITLE
Script becomes completed right at the start 

### ISSUE THREAD

**Issue by simonelmundo** [sheldonchiu/AI-AIO#22]
The script becomes ‘completed’ right after I launch my notebook, and none of the expected actions happen: no downloaded models, no Cloudflare tunnel launching..... It seems like the script stops at the very beginning. How can I troubleshoot this issue? 
![Screenshot 2023-09-23 104331](https://github.com/sheldonchiu/AI-AIO/assets/145836062/05d4e730-9803-447f-be3e-dd4022899407)

**Comment by sheldonchiu** [comment]
hi, please provide the output of `env` and `cat /tmp/run.log`

**Comment by simonelmundo** [comment]
Hello! where do I find that?

**Comment by sheldonchiu** [comment]
execute this two command in the terminal and copy the output

**Comment by simonelmundo** [comment]
env : root@nnbym7bqki:/notebooks# env
SHELL=/bin/bash
NVIDIA_VISIBLE_DEVICES=GPU-73a03922-87a1-2ff8-96ae-1dd0e9748d4e
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
COMMAND_USERNAME=test
PAPERSPACE_METRIC_WORKLOAD_ID=nnbym7bqki
HOSTNAME=nnbym7bqki
DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1151072841710714940/anOjbgYzjTNdNlOMC0_w98QTcevOEZ4e8fYVTNENaw_dUjdxDm9xfeYhrQjcb5A7MCAw
MODEL_LIST= https://civitai.com/api/download/models/70977?type=Model&format=SafeTensor&size=pruned&fp=fp16,https://civitai.com/api/download/models/100043,https://civitai.com/api/download/models/46846,https://civitai.com/api/download/models/22258

PWD=/notebooks
JUPYTER_TOKEN=b7cba5ff016b1ea23e01f862f8348b31
JUPYTER_SERVER_URL=http://nnbym7bqki:8890/
RUN_SCRIPT=command,sd_webui,image_browser
LINES=40
IMAGE_BROWSER_KEY=
HOME=/root
LANG=C.UTF-8
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
COLUMNS=184
PAPERSPACE_FQDN=nnbym7bqki.clg07azjl.paperspacegradient.com
PYDEVD_USE_FRAME_EVAL=NO
EMBEDDING_LIST=https://civitai.com/api/download/models/77169,https://civitai.com/api/download/models/77173,https://civitai.com/api/download/models/94057
CONTROLNET_LIST=https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11f1e_sd15_tile.pth,
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11f1p_sd15_depth.pth,
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_inpaint.pth,
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_lineart.pth,
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_openpose.pth,
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_canny.pth
PIP_INSTALL=python3 -m pip --no-cache-dir install --upgrade
EXTRA_SD_WEBUI_ARGS=
LORA_LIST=https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors,https://civitai.com/api/download/models/92193,https://civitai.com/api/download/models/62512,https://civitai.com/api/download/models/8114,https://civitai.com/api/download/models/55477,https://civitai.com/api/download/models/25804,https://civitai.com/api/download/models/56520,https://civitai.com/api/download/models/56381,https://civitai.com/api/download/models/115535,https://civitai.com/api/download/models/67060,https://civitai.com/api/download/models/87355,https://civitai.com/api/download/models/17093,https://civitai.com/api/download/models/33458,https://civitai.com/api/download/models/18310,https://civitai.com/api/download/models/120989,https://civitai.com/api/download/models/101842,https://civitai.com/api/download/models/95399,https://civitai.com/api/download/models/116247,https://civitai.com/api/download/models/20099,https://civitai.com/api/download/models/88753,https://civitai.com/api/download/models/37451,https://civitai.com/api/download/models/129032,https://civitai.com/api/download/models/23252,https://civitai.com/api/download/models/128897,https://civitai.com/api/download/models/33314,https://civitai.com/api/download/models/86868,https://civitai.com/api/download/models/96107,https://civitai.com/api/download/models/64344,https://civitai.com/api/download/models/21538
JUPYTER_SERVER_ROOT=/notebooks
TERM=xterm-256color
COMMAND_PASSWORD=test
SD_WEBUI_UPDATE_REPO=auto
SHLVL=1
PAPERSPACE_CLUSTER_ID=clg07azjl
PYXTERM_DIMENSIONS=80x25
APT_INSTALL=apt-get install -y --no-install-recommends
KUBERNETES_PORT_443_TCP_PROTO=tcp
PAPERSPACE_NOTEBOOK_ID=nnbym7bqki
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64
GIT_PYTHON_REFRESH=quiet
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
VAE_LIST=https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors,https://civitai.com/api/download/models/28569
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin:/usr/local/cuda-11.6/bin
GIT_CLONE=git clone --depth 10
DISABLE_JUPYTER=true
DEBIAN_FRONTEND=noninteractive
PAPERSPACE_NOTEBOOK_REPO_ID=rse85bm8euemll1
PAPERSPACE_METRIC_WORKLOAD_TYPE=notebook
_=/usr/bin/env
...............................................................
Installing common dependencies
Starting script(s)
### Command received ###
[2023-09-23 08:20:59] Reloading Command Server
[2023-09-23 08:20:59] Error: PID file /tmp/command.pid not found!
### Setting up Command Server ###
[2023-09-23 08:21:00] Setting up Command Server
Requirement already satisfied: pip in /tmp/command-env/lib/python3.9/site-packages (22.0.4)
Collecting pip
  Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 95.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.2.1
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: setuptools in /tmp/command-env/lib/python3.9/site-packages (58.1.0)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
  Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 14.9 MB/s eta 0:00:00
Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 86.0 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-68.2.2 wheel-0.41.2
Collecting fastapi
  Obtaining dependency information for fastapi from https://files.pythonhosted.org/packages/76/e5/ca411b260caa4e72f9ac5482f331fe74fd4eb5b97aa74d1d2806ccf07e2c/fastapi-0.103.1-py3-none-any.whl.metadata
  Downloading fastapi-0.103.1-py3-none-any.whl.metadata (24 kB)
Collecting uvicorn[standard]
  Obtaining dependency information for uvicorn[standard] from https://files.pythonhosted.org/packages/79/96/b0882a1c3f7ef3dd86879e041212ae5b62b4bd352320889231cc735a8e8f/uvicorn-0.23.2-py3-none-any.whl.metadata
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting psutil
  Downloading psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.1/282.1 kB 50.4 MB/s eta 0:00:00
Collecting anyio<4.0.0,>=3.7.1 (from fastapi)
  Obtaining dependency information for anyio<4.0.0,>=3.7.1 from https://files.pythonhosted.org/packages/19/24/44299477fe7dcc9cb58d0a57d5a7588d6af2ff403fdd2d47a246c91a3246/anyio-3.7.1-py3-none-any.whl.metadata
  Downloading anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 (from fastapi)
  Obtaining dependency information for pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 from https://files.pythonhosted.org/packages/82/06/fafdc75e48b248eff364b4249af4bcc6952225e8f20e8205820afc66e88e/pydantic-2.3.0-py3-none-any.whl.metadata
  Downloading pydantic-2.3.0-py3-none-any.whl.metadata (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 45.7 MB/s eta 0:00:00
Collecting starlette<0.28.0,>=0.27.0 (from fastapi)
  Obtaining dependency information for starlette<0.28.0,>=0.27.0 from https://files.pythonhosted.org/packages/58/f8/e2cca22387965584a409795913b774235752be4176d276714e15e1a58884/starlette-0.27.0-py3-none-any.whl.metadata
  Downloading starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
Collecting typing-extensions>=4.5.0 (from fastapi)
  Obtaining dependency information for typing-extensions>=4.5.0 from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting click>=7.0 (from uvicorn[standard])
  Obtaining dependency information for click>=7.0 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting h11>=0.8 (from uvicorn[standard])
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 19.7 MB/s eta 0:00:00
Collecting httptools>=0.5.0 (from uvicorn[standard])
  Obtaining dependency information for httptools>=0.5.0 from https://files.pythonhosted.org/packages/28/7c/5ddc99737fb141bd9077f45af23e9d3c83496b4c04bf463e4e72f57043cd/httptools-0.6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading httptools-0.6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard])
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml>=5.1 (from uvicorn[standard])
  Obtaining dependency information for pyyaml>=5.1 from https://files.pythonhosted.org/packages/7d/39/472f2554a0f1e825bd7c5afc11c817cd7a2f3657460f7159f691fbb37c51/PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard])
  Downloading uvloop-0.17.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 60.8 MB/s eta 0:00:00
Collecting watchfiles>=0.13 (from uvicorn[standard])
  Obtaining dependency information for watchfiles>=0.13 from https://files.pythonhosted.org/packages/e1/46/c9d5ee4871b187d291d62e61c41f9a4d67d4866a89704b0ad16b6949e9bd/watchfiles-0.20.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading watchfiles-0.20.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting websockets>=10.4 (from uvicorn[standard])
  Downloading websockets-11.0.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.7/129.7 kB 42.6 MB/s eta 0:00:00
Collecting idna>=2.8 (from anyio<4.0.0,>=3.7.1->fastapi)
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 17.6 MB/s eta 0:00:00
Collecting sniffio>=1.1 (from anyio<4.0.0,>=3.7.1->fastapi)
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting exceptiongroup (from anyio<4.0.0,>=3.7.1->fastapi)
  Obtaining dependency information for exceptiongroup from https://files.pythonhosted.org/packages/ad/83/b71e58666f156a39fb29417e4c8ca4bc7400c0dd4ed9e8842ab54dc8c344/exceptiongroup-1.1.3-py3-none-any.whl.metadata
  Downloading exceptiongroup-1.1.3-py3-none-any.whl.metadata (6.1 kB)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/d8/f0/a2ee543a96cc624c35a9086f39b1ed2aa403c6d355dfe47a11ee5c64a164/annotated_types-0.5.0-py3-none-any.whl.metadata
  Downloading annotated_types-0.5.0-py3-none-any.whl.metadata (11 kB)
Collecting pydantic-core==2.6.3 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi)
  Obtaining dependency information for pydantic-core==2.6.3 from https://files.pythonhosted.org/packages/18/54/6d64dff3e49e7faf4f5b989b49e46dd8b592d1e3f3db2113f4aaf1defdd3/pydantic_core-2.6.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading pydantic_core-2.6.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Downloading fastapi-0.103.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.2/66.2 kB 23.6 MB/s eta 0:00:00
Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 30.7 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 35.1 MB/s eta 0:00:00
Downloading httptools-0.6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (432 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.5/432.5 kB 53.2 MB/s eta 0:00:00
Downloading pydantic-2.3.0-py3-none-any.whl (374 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.5/374.5 kB 47.2 MB/s eta 0:00:00
Downloading pydantic_core-2.6.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 69.8 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.9/738.9 kB 60.6 MB/s eta 0:00:00
Downloading starlette-0.27.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 kB 25.1 MB/s eta 0:00:00
Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading watchfiles-0.20.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.4 MB/s eta 0:00:00
Downloading uvicorn-0.23.2-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 21.8 MB/s eta 0:00:00
Downloading annotated_types-0.5.0-py3-none-any.whl (11 kB)
Downloading exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Installing collected packages: websockets, uvloop, typing-extensions, sniffio, pyyaml, python-dotenv, psutil, idna, httptools, h11, exceptiongroup, click, annotated-types, uvicorn, pydantic-core, anyio, watchfiles, starlette, pydantic, fastapi
Successfully installed annotated-types-0.5.0 anyio-3.7.1 click-8.1.7 exceptiongroup-1.1.3 fastapi-0.103.1 h11-0.14.0 httptools-0.6.0 idna-3.4 psutil-5.9.5 pydantic-2.3.0 pydantic-core-2.6.3 python-dotenv-1.0.0 pyyaml-6.0.1 sniffio-1.3.0 starlette-0.27.0 typing-extensions-4.8.0 uvicorn-0.23.2 uvloop-0.17.0 watchfiles-0.20.0 websockets-11.0.3
[2023-09-23 08:21:09] Finished Preparing Environment for Command Server
### Starting Command Server ###
[2023-09-23 08:21:09] Starting Command Server
[2023-09-23 08:21:09] Command Server Started
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58    0     0  100    58      0    195 --:--:-- --:--:-- --:--:--   195
[2023-09-23 08:21:09] Link: https://nnbym7bqki.clg07azjl.paperspacegradient.com/command/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   102    0     0  100   102      0     19  0:00:05  0:00:05 --:--:--    22
### Done ###
### Done ###
### Command received ###
[2023-09-23 08:21:14] Reloading Stable Diffusion WebUI
[2023-09-23 08:21:14] Error: PID file /tmp/sd_webui.pid not found!
### Setting up Stable Diffusion WebUI ###
[2023-09-23 08:21:15] Setting up Stable Diffusion WebUI
[2023-09-23 08:21:15] Updating Repo /storage/stable-diffusion-webui ...
Already up to date.
[2023-09-23 08:21:16] /storage/stable-diffusion-webui/outputs -> /storage/image_outputs/stable-diffusion-webui
[2023-09-23 08:21:16] /tmp/stable-diffusion-models -> /notebooks/models
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/sd -> /storage/stable-diffusion-webui/models/Stable-diffusion
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/lora -> /storage/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/lora -> /storage/stable-diffusion-webui/models/Lora
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/vae -> /storage/stable-diffusion-webui/models/VAE
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/hypernetwork -> /storage/stable-diffusion-webui/models/hypernetworks
[2023-09-23 08:21:16] /tmp/stable-diffusion-models/embedding -> /storage/stable-diffusion-webui/embeddings
### Command received ###
[2023-09-23 08:21:16] Reloading Image Browser
[2023-09-23 08:21:16] Error: PID file /tmp/image_browser.pid not found!
### Setting up Image Browser ###
[2023-09-23 08:21:17] Setting up Image Browser
[2023-09-23 08:21:17] Updating Repo /storage/sd-webui-infinite-image-browsing ...
root@nnbym7bqki:/notebooks#

**Comment by sheldonchiu** [comment]
hi, please run this command `cd /notebooks/sd_webui && bash control.sh reload` and see if it output any error

**Comment by simonelmundo** [comment]
### Command received ###
[2023-09-23 09:21:59] Reloading Stable Diffusion WebUI
[2023-09-23 09:21:59] Error: PID file /tmp/sd_webui.pid not found!
### Setting up Stable Diffusion WebUI ###
[2023-09-23 09:22:00] Setting up Stable Diffusion WebUI
[2023-09-23 09:22:00] Updating Repo /storage/stable-diffusion-webui ...
Already up to date.
[2023-09-23 09:22:02] /storage/stable-diffusion-webui/outputs -> /storage/image_outputs/stable-diffusion-webui
[2023-09-23 09:22:02] /tmp/stable-diffusion-models -> /notebooks/models
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/sd -> /storage/stable-diffusion-webui/models/Stable-diffusion
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/lora -> /storage/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/lora -> /storage/stable-diffusion-webui/models/Lora
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/vae -> /storage/stable-diffusion-webui/models/VAE
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/hypernetwork -> /storage/stable-diffusion-webui/models/hypernetworks
[2023-09-23 09:22:02] /tmp/stable-diffusion-models/embedding -> /storage/stable-diffusion-webui/embeddings
cp: cannot stat '/storage/stable-diffusion-webui/extensions/sd-webui-controlnet/models/*.yaml': No such file or directory
### ERROR ###
### ERROR ###
root@nnbym7bqki:/notebooks/sd_webui#

**Comment by sheldonchiu** [comment]
something is wrong with setting up controlnet, I have applied a temp workaround. Please run `cd /notebooks && git pull && cd sd_webui && bash control.sh reload` to start webui

**Comment by simonelmundo** [comment]
Do i start a new notebook? or the same one that I have already open?

**Comment by sheldonchiu** [comment]
run `cd /notebooks && git pull && cd sd_webui && bash control.sh reload`  in your current notebook is enough

**Comment by simonelmundo** [comment]
I did it in the same notebook, model are getting downloaded now. seems like things are working for now...

**Comment by simonelmundo** [comment]
It worked!!! Whatever you changed you tech wizard worked! I just generated my first image. thank you

**Comment by sheldonchiu** [comment]
Enjoy your AI journey~~ Feel free to open a new ticket when you encounter a new issue.

**Comment by sheldonchiu** [comment]
if you are not seeing any controlnet model, just run `cd /notebooks && git pull && cd sd_webui && bash control.sh reload` again to update the tool and restart webui
