### ISSUE TITLE
Web ui Extensions

### ISSUE THREAD

**Issue by simonelmundo** [sheldonchiu/AI-AIO#23]
Hello, I checked the tutorial, but the web ui you had on it is different that the one I have 
![Screenshot 2023-09-23 124333](https://github.com/sheldonchiu/AI-AIO/assets/145836062/3ec5b344-509d-4c05-a1c6-0e21fa735029)
I'm missing lot of extensions and features . 
How do I get the same web ui as you had?

**Comment by sheldonchiu** [comment]
For webui extensions, use the extension tab and install the desired extension

**Comment by simonelmundo** [comment]
is there a way to load it before? and install the extensions with the models and loras and get a web-ui like the one you had :
![Screenshot 2023-09-23 140904](https://github.com/sheldonchiu/AI-AIO/assets/145836062/98ba398a-4349-4c34-8195-281c3954fd35)

**Comment by sheldonchiu** [comment]
The list of extensions is very very long, and constantly updating. Too much extensions could be overwhelming for beginners, and I recommend trying it one by one.

To learn more about extension, you can take a look at this https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions

Some extensions that I have used is:
1. MultiDiffusion with Tiled VAE
2. OpenPose Editor
3. Catppuccin themes

You just have to install the extension once, it will still be there next time you start a new notebook

**Comment by simonelmundo** [comment]
"You just have to install the extension once, it will still be there next time you start a new notebook"
Oh! is that so! then It won't be a problem! I thought I had to install the extensions every time I have to start a new notebook from the extensions tab. How is it possible that it remembers the extensions I installed? where does it get stored, I thought i start a blank new notebook every time.... 
Anyway, thank you! I hope it doesn't bother you with all the issues im opening.

**Comment by sheldonchiu** [comment]
For pro tier user, papersapce provide 15GB of free storage. All tools related files and image outputs are stored inside this storage, which is shared across all your notebooks.

Model files are downloaded every time you start a new notebook to save space.
